theme: minima

title: Achyutha Ashish
tagline: Engineering, Embedded Systems & Software and insights on tech & life
description: "Welcome to my personal site where I share projects, deep dives into tech, and stories from my journey."
url: "https://AchyuthaAshish.github.io" # Replace with your custom domain if you have one
baseurl: "/skills-github-pages" # Repository name

header_pages:
  - about.md
# Author Details
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
